export const categories = [
  { id: 1, identifier: "all", name: "All Items", icon: "ri-grid-fill" },
  { id: 2, identifier: "salads", name: "Salads", icon: "ri-leaf-line" },
  {
    id: 3,
    identifier: "sandwiches",
    name: "Sandwiches",
    icon: "ri-restaurant-line",
  },
  { id: 4, identifier: "desserts", name: "Desserts", icon: "ri-cake-3-line" },
  { id: 5, identifier: "drinks", name: "Drinks", icon: "ri-cup-line" },
  {
    id: 6,
    identifier: "burgers",
    name: "Burgers",
    icon: "ri-restaurant-2-line",
  },
];

export const featuredMeals = [
  {
    id: 1,
    title: "Berries Salad",
    price: 5.0,
    rating: 5.0,
    image:
      "https://www.inspiredtaste.net/wp-content/uploads/2024/07/Berry-Salad-Recipe.jpg",
  },
  {
    id: 2,
    title: "Chicken Bowl",
    price: 8.5,
    rating: 4.8,
    image:
      "https://healthyfitnessmeals.com/wp-content/uploads/2018/08/Grilled-chicken-burrito-bowls-10.jpg",
  },
  {
    id: 3,
    title: "Vegan Mix Plate",
    price: 6.5,
    rating: 4.6,
    image:
      "https://thumbs.dreamstime.com/b/woman-holds-plate-frozen-vegetable-mix-corn-peas-beans-carrots-frozen-veggie-mix-white-plate-diet-proper-nutrition-healthy-385707931.jpg",
  },
  {
    id: 4,
    title: "Fruit Yogurt",
    price: 4.0,
    rating: 4.9,
    image:
      "https://www.gatheranddine.com/wp-content/uploads/2014/06/Fruit-Yogurt-Nut-Plate-3.jpg",
  },
  {
    id: 5,
    title: "Grilled Salmon",
    price: 12.0,
    rating: 4.7,
    image:
      "https://res.cloudinary.com/hksqkdlah/image/upload/c_fill,dpr_2.0,f_auto,fl_lossy.progressive.strip_profile,g_faces:auto,q_auto:low/41765-sfs-grilled-salmon-10664",
  },
  {
    id: 6,
    title: "Beef Burger",
    price: 9.0,
    rating: 4.8,
    image:
      "https://www.puregoldpineapples.com.au/wp-content/uploads/2020/10/aussie-beef-burger.jpg",
  },
  {
    id: 7,
    title: "Pasta Alfredo",
    price: 7.5,
    rating: 4.5,
    image:
      "https://www.allrecipes.com/thmb/gTibTRJ8MW87L0jMhAvXPjIDD94=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/19402-quick-and-easy-alfredo-sauce-DDMFS-4x3-17abb2055c714807944172db9172b045.jpg",
  },
  {
    id: 8,
    title: "Avocado Toast",
    price: 4.8,
    rating: 4.6,
    image:
      "https://www.allrecipes.com/thmb/8NccFzsaq0_OZPDKmf7Yee-aG78=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AvocadoToastwithEggFranceC4x3-bb87e3bbf1944657b7db35f1383fabdb.jpg",
  },
  {
    id: 9,
    title: "Chicken Wrap",
    price: 6.0,
    rating: 4.4,
    image:
      "https://simply-delicious-food.com/wp-content/uploads/2019/04/tzatziki-chicken-wraps-1.jpg",
  },
  {
    id: 10,
    title: "Chocolate Dessert",
    price: 5.5,
    rating: 4.9,
    image:
      "https://www.simplyrecipes.com/thmb/YayUyD02pu4U1mshxPwwNIArnjQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/simply-recipes-chocolate-delight-lead-10-03261d5d6f6144789ada0586e20ea8e2.jpg",
  },
];

export const topChefs = [
  {
    id: 1,
    title: "Mark Henry",
    description: "specialized in chineese foods",
    image: "https://thumbs.dreamstime.com/b/female-chef-14984977.jpg",
  },
  {
    id: 2,
    title: "Lucky Helen",
    description: "specialized in Italian foods",
    image:
      "https://i.pinimg.com/736x/a7/fc/f5/a7fcf5f67501543a57a42d7b29534623.jpg",
  },
  {
    id: 3,
    title: "Moon Henry",
    description: "specialized in thai foods",
    image:
      "https://www.shutterstock.com/image-photo/restaurant-kitchen-portrait-confident-chef-600nw-2645077225.jpg",
  },
  {
    id: 4,
    title: "Tom Monrow",
    description: "specialized in continetal foods",
    image:
      "https://i.pinimg.com/736x/b7/91/c0/b791c07c2692132f521d4e18b621c664.jpg",
  },
];

export const menuItems = [
  {
    id: 1,
    title: "Healthy Salad",
    category: "salads",
    price: 23.0,
    rating: 5.0,
    calories: 450,
    prepTime: "15-20",
    description: "Fresh mixed greens with grilled chicken and quinoa",
    ingredients: [
      "Mixed Greens",
      "Grilled Chicken",
      "Quinoa",
      "Cherry Tomatoes",
      "Cucumber",
      "Avocado",
      "House Dressing",
    ],
    images: [
      "https://readdy.ai/api/search-image?query=fresh%20healthy%20salad%20bowl%20with%20grilled%20chicken%20quinoa%20mixed%20greens%20cherry%20tomatoes%20cucumber%20avocado%20on%20clean%20white%20background%20professional%20food%20photography%20vibrant%20colors%20top%20view&width=800&height=800&seq=menudetail1&orientation=squarish",
      "https://readdy.ai/api/search-image?query=healthy%20salad%20bowl%20close%20up%20showing%20fresh%20ingredients%20grilled%20chicken%20quinoa%20vegetables%20on%20clean%20white%20background%20professional%20food%20photography&width=800&height=800&seq=menudetail2&orientation=squarish",
      "https://readdy.ai/api/search-image?query=salad%20bowl%20side%20angle%20view%20with%20colorful%20vegetables%20chicken%20quinoa%20on%20clean%20white%20background%20professional%20food%20photography&width=800&height=800&seq=menudetail3&orientation=squarish",
      "https://readdy.ai/api/search-image?query=healthy%20salad%20bowl%20ingredients%20layout%20fresh%20vegetables%20chicken%20quinoa%20on%20clean%20white%20background%20professional%20food%20photography&width=800&height=800&seq=menudetail4&orientation=squarish",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 2,
    title: "Caesar Salad",
    category: "salads",
    price: 43.5,
    rating: 4.8,
    calories: 420,
    prepTime: "10-15",
    description: "Classic caesar with parmesan and croutons",
    ingredients: ["Romaine Lettuce", "Parmesan", "Croutons", "Caesar Dressing"],
    images: [
      "https://readdy.ai/api/search-image?query=fresh%20caesar%20salad%20with%20parmesan%20cheese%20croutons%20romaine%20lettuce%20on%20white%20plate%20simple%20clean%20white%20background%20professional%20food%20photography&width=400&height=400&seq=salad2&orientation=squarish",
      "../assets/Caesar-Salad1.jpg",
      "../assets/Caesar-Salad2.jpg",
      "../assets/Caesar-Salad3.jpg",
    ],
    popular: false,
    stock: 12,
    sales: 12,
    status: true,
  },

  {
    id: 3,
    title: "Greek Salad",
    category: "salads",
    price: 24.0,
    rating: 4.9,
    calories: 400,
    prepTime: "10-15",
    description: "Fresh vegetables with feta cheese and olives",
    ingredients: ["Tomatoes", "Cucumber", "Feta", "Olives", "Olive Oil"],
    images: [
      "https://readdy.ai/api/search-image?query=greek%20salad%20with%20feta%20cheese%20olives%20tomatoes%20cucumber%20on%20white%20plate%20simple%20clean%20white%20background%20professional%20food%20photography&width=400&height=400&seq=salad3&orientation=squarish",
      "../assets/greek-Salad-_0000_2.jpg",
      "../assets/greek-Salad-_0000_1.jpg",
      "../assets/greek-Salad-_0000_3.jpg",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: false,
  },

  {
    id: 4,
    title: "Chicken Avocado Salad",
    category: "salads",
    price: 55.0,
    rating: 4.7,
    calories: 480,
    prepTime: "15",
    description: "Grilled chicken with avocado and greens",
    ingredients: ["Chicken", "Avocado", "Lettuce", "Tomatoes"],
    images: [
      "../assets/avacado-chicken-Salad_1.jpg",
      "../assets/avacado-chicken-Salad_2.jpg",
      "../assets/avacado-chicken-Salad_3.jpg",
      "../assets/avacado-chicken-Salad_4.jpg",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 5,
    title: "Club Sandwich",
    category: "sandwiches",
    price: 15.5,
    rating: 4.7,
    calories: 550,
    prepTime: "15-20",
    description: "Triple decker with chicken, bacon, and vegetables",
    ingredients: ["Bread", "Chicken", "Bacon", "Lettuce", "Tomato"],
    images: [
      "../assets/Club-Sandwitch_1.png",
      "../assets/Club-Sandwitch_2.png",
      "../assets/Club-Sandwitch_3.png",
      "../assets/Club-Sandwitch_4.png",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 6,
    title: "Grilled Cheese",
    category: "sandwiches",
    price: 13.5,
    rating: 4.6,
    calories: 500,
    prepTime: "10",
    description: "Classic grilled cheese sandwich",
    ingredients: ["Bread", "Cheddar Cheese", "Butter"],
    images: [
      "../assets/grill-cheese-sandwitch (1).jpg",
      "../assets/grill-cheese-sandwitch (2).jpg",
      "../assets/grill-cheese-sandwitch (3).jpg",
      "../assets/grill-cheese-sandwitch (4).jpg",
    ],
    popular: false,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 7,
    title: "BLT Sandwich",
    category: "sandwiches",
    price: 14.5,
    rating: 4.8,
    calories: 520,
    prepTime: "12",
    description: "Bacon, lettuce, and tomato on toasted bread",
    ingredients: ["Bacon", "Lettuce", "Tomato", "Bread"],
    images: [
      "../assets/blt-sandwitch (1).jpg",
      "../assets/blt-sandwitch (2).jpg",
      "../assets/blt-sandwitch (3).jpg",
      "../assets/blt-sandwitch (4).jpg",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 8,
    title: "Veggie Sandwich",
    category: "sandwiches",
    price: 14.0,
    rating: 4.5,
    calories: 430,
    prepTime: "10",
    description: "Grilled vegetables with hummus",
    ingredients: ["Zucchini", "Bell Peppers", "Hummus", "Bread"],
    images: [
      "../assets/Veggie-Sandwich (1).jpg",
      "../assets/Veggie-Sandwich (2).jpg",
      "../assets/Veggie-Sandwich (3).jpg",
      "../assets/Veggie-Sandwich (4).jpg",
    ],
    popular: false,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 9,
    title: "Classic Burger",
    category: "burgers",
    price: 16.0,
    rating: 4.9,
    calories: 650,
    prepTime: "15",
    description: "Beef patty with cheese, lettuce, and tomato",
    ingredients: ["Beef Patty", "Cheese", "Lettuce", "Tomato", "Bun"],
    images: [
      "../assets/classic-burger (1).jpg",
      "../assets/classic-burger (2).jpg",
      "../assets/classic-burger (3).jpg",
      "../assets/classic-burger (4).jpg",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: false,
  },

  {
    id: 10,
    title: "Chicken Burger",
    category: "burgers",
    price: 25.5,
    rating: 4.7,
    calories: 600,
    prepTime: "15",
    description: "Grilled chicken with special sauce",
    ingredients: ["Chicken Patty", "Lettuce", "Sauce", "Bun"],
    images: [
      "../assets/chicken-burger (1).jpg",
      "../assets/chicken-burger (2).jpg",
      "../assets/chicken-burger (3).jpg",
      "../assets/chicken-burger (4).jpg",
    ],
    popular: false,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 11,
    title: "Veggie Burger",
    category: "burgers",
    price: 25.0,
    rating: 4.6,
    calories: 580,
    prepTime: "15",
    description: "Plant-based patty with fresh vegetables",
    ingredients: ["Veggie Patty", "Lettuce", "Tomato", "Bun"],
    images: [
      "../assets/veggie-burger.jpg",
      "../assets/veggie-burger (2).jpg",
      "../assets/veggie-burger (3).jpg",
      "../assets/veggie-burger (4).jpg",
    ],
    popular: false,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 12,
    title: "Chocolate Cake",
    category: "desserts",
    price: 140.0,
    rating: 5.0,
    calories: 600,
    prepTime: "20",
    description: "Rich chocolate layer cake with frosting",
    ingredients: ["Cocoa", "Flour", "Sugar", "Eggs", "Butter"],
    images: [
      "../assets/chocolate-cake.jpg",
      "../assets/chocolate-cake (2).jpg",
      "../assets/chocolate-cake (3).jpg",
      "../assets/chocolate-cake (4).jpg",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 13,
    title: "Cheesecake",
    category: "desserts",
    price: 40.5,
    rating: 4.9,
    calories: 620,
    prepTime: "25",
    description: "New York style cheesecake",
    ingredients: ["Cream Cheese", "Sugar", "Eggs", "Biscuit Base"],
    images: [
      "../assets/cheese-cake (1).jpg",
      "../assets/cheese-cake (2).jpg",
      "../assets/cheese-cake (3).jpg",
      "../assets/cheese-cake (4).jpg",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: false,
  },

  {
    id: 14,
    title: "Tiramisu",
    category: "desserts",
    price: 55.0,
    rating: 4.8,
    calories: 590,
    prepTime: "25",
    description: "Italian coffee-flavored dessert",
    ingredients: ["Mascarpone", "Coffee", "Cocoa", "Ladyfingers"],
    images: [
      "../assets/Tramisu (1).jpg",
      "../assets/Tramisu (2).jpg",
      "../assets/Tramisu (3).jpg",
      "../assets/Tramisu (4).jpg",
    ],
    popular: false,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 15,
    title: "Brownie",
    category: "desserts",
    price: 34.5,
    rating: 4.7,
    calories: 520,
    prepTime: "20",
    description: "Fudgy chocolate brownie",
    ingredients: ["Chocolate", "Flour", "Sugar", "Butter"],
    images: [
      "../assets/Brownie (1).jpg",
      "../assets/Brownie (2).jpg",
      "../assets/Brownie (3).jpg",
      "../assets/Brownie (4).jpg",
    ],
    popular: false,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 16,
    title: "Fresh Orange Juice",
    category: "drinks",
    price: 25.5,
    rating: 4.7,
    calories: 120,
    prepTime: "5",
    description: "Freshly squeezed orange juice",
    ingredients: ["Oranges"],
    images: [
      "../assets/Orange-Juice (1).jpg",
      "../assets/Orange-Juice (2).jpg",
      "../assets/Orange-Juice (3).jpg",
      "../assets/Orange-Juice (4).jpg",
    ],
    popular: false,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 17,
    title: "Green Smoothie",
    category: "drinks",
    price: 23.5,
    rating: 4.8,
    calories: 180,
    prepTime: "5",
    description: "Spinach, banana, and mango blend",
    ingredients: ["Spinach", "Banana", "Mango"],
    images: [
      "../assets/GreenSmoothie (1).jpg",
      "../assets/GreenSmoothie (2).jpg",
      "../assets/GreenSmoothie (3).jpg",
      "../assets/GreenSmoothie (4).jpg",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 18,
    title: "Iced Coffee",
    category: "drinks",
    price: 23.0,
    rating: 4.6,
    calories: 90,
    prepTime: "5",
    description: "Cold brew coffee with ice",
    ingredients: ["Coffee", "Ice"],
    images: [
      "../assets/Iced_Coffee (1).jpg",
      "../assets/Iced_Coffee (2).jpg",
      "../assets/Iced_Coffee (3).jpg",
      "../assets/Iced_Coffee (4).jpg",
    ],
    popular: false,
    stock: 23,
    sales: 120,
    status: false,
  },

  {
    id: 19,
    title: "Lemonade",
    category: "drinks",
    price: 23.8,
    rating: 4.5,
    calories: 110,
    prepTime: "5",
    description: "Fresh lemon juice with mint",
    ingredients: ["Lemon", "Sugar", "Mint"],
    images: [
      "../assets/lemonade (1).jpg",
      "../assets/lemonade (2).jpg",
      "../assets/lemonade (3).jpg",
      "../assets/lemonade (4).jpg",
    ],
    popular: false,
    stock: 23,
    sales: 120,
    status: true,
  },

  {
    id: 20,
    title: "Strawberry Milkshake",
    category: "drinks",
    price: 44.0,
    rating: 4.9,
    calories: 300,
    prepTime: "7",
    description: "Creamy strawberry milkshake",
    ingredients: ["Strawberries", "Milk", "Ice Cream"],
    images: [
      "../assets/Strawberry-Milkshake (1).jpg",
      "../assets/Strawberry-Milkshake (2).jpg",
      "../assets/Strawberry-Milkshake (3).jpg",
      "../assets/Strawberry-Milkshake (4).jpg",
    ],
    popular: true,
    stock: 23,
    sales: 120,
    status: true,
  },
];

export const stats = [
  {
    label: "Total Dishes",
    value: menuItems.length.toString(),
    icon: "ri-restaurant-line",
    color: "bg-blue-500",
  },
  {
    label: "Active Orders",
    value: "23",
    icon: "ri-shopping-bag-line",
    color: "bg-green-500",
  },
  {
    label: "Total Revenue",
    value: "$12,450",
    icon: "ri-money-dollar-circle-line",
    color: "bg-orange-500",
  },
  {
    label: "Customers",
    value: "1,234",
    icon: "ri-user-line",
    color: "bg-purple-500",
  },
];
export const diliveryDriver = [
  {
    id: 1,
    name: "John Smith",
    phone: "+1 (555) 987-6543",
    rating: 4.9,
    vehicle: "Honda Civic - ABC 1234",
  },
  {
    id: 2,
    name: "Michael Johnson",
    phone: "+1 (555) 234-7890",
    rating: 4.7,
    vehicle: "Toyota Corolla - XYZ 5678",
  },
  {
    id: 3,
    name: "David Williams",
    phone: "+1 (555) 456-1122",
    rating: 4.8,
    vehicle: "Suzuki Alto - DEF 9012",
  },
  {
    id: 4,
    name: "Chris Brown",
    phone: "+1 (555) 778-3344",
    rating: 4.6,
    vehicle: "Honda City - GHI 3456",
  },
  {
    id: 5,
    name: "Daniel Miller",
    phone: "+1 (555) 889-5566",
    rating: 4.5,
    vehicle: "Yamaha Bike - JKL 7890",
  },
  {
    id: 6,
    name: "Andrew Wilson",
    phone: "+1 (555) 101-2020",
    rating: 4.9,
    vehicle: "Toyota Yaris - MNO 4321",
  },
  {
    id: 7,
    name: "Robert Taylor",
    phone: "+1 (555) 303-4040",
    rating: 4.4,
    vehicle: "Honda CD 70 - PQR 8765",
  },
];

export const allIngredients = [
  // 🥬 Greens & Vegetables
  "Mixed Greens",
  "Romaine Lettuce",
  "Iceberg Lettuce",
  "Spinach",
  "Arugula",
  "Kale",
  "Cabbage",
  "Red Cabbage",
  "Carrot",
  "Cherry Tomatoes",
  "Tomatoes",
  "Cucumber",
  "Onion",
  "Red Onion",
  "Green Onion",
  "Bell Pepper",
  "Green Bell Pepper",
  "Red Bell Pepper",
  "Yellow Bell Pepper",
  "Zucchini",
  "Broccoli",
  "Cauliflower",
  "Mushrooms",
  "Olives",
  "Pickles",
  "Jalapeños",
  "Corn",
  "Peas",
  "Garlic",
  "Ginger",
  "Beetroot",
  "Sweet Potato",
  "Potato",
  "Avocado",

  // 🍗 Proteins (Meat & Alternatives)
  "Grilled Chicken",
  "Chicken Breast",
  "Chicken Thigh",
  "Fried Chicken",
  "Beef",
  "Beef Patty",
  "Steak",
  "Minced Beef",
  "Lamb",
  "Turkey",
  "Bacon",
  "Ham",
  "Sausage",
  "Pepperoni",
  "Fish Fillet",
  "Tuna",
  "Salmon",
  "Shrimp",
  "Prawns",
  "Egg",
  "Boiled Egg",
  "Fried Egg",
  "Tofu",
  "Paneer",
  "Tempeh",

  // 🧀 Dairy & Cheese
  "Cheddar Cheese",
  "Mozzarella",
  "Parmesan",
  "Swiss Cheese",
  "Feta Cheese",
  "Cream Cheese",
  "Butter",
  "Milk",
  "Yogurt",
  "Sour Cream",
  "Whipping Cream",

  // 🌾 Grains, Bread & Carbs
  "White Rice",
  "Brown Rice",
  "Basmati Rice",
  "Quinoa",
  "Couscous",
  "Pasta",
  "Spaghetti",
  "Penne",
  "Lasagna Sheets",
  "Bread",
  "Burger Bun",
  "Hot Dog Bun",
  "Wrap",
  "Tortilla",
  "Pizza Dough",
  "Croutons",
  "Oats",

  // 🥫 Sauces & Dressings
  "House Dressing",
  "Caesar Dressing",
  "Ranch Dressing",
  "Italian Dressing",
  "Vinaigrette",
  "Mayonnaise",
  "Ketchup",
  "Mustard",
  "BBQ Sauce",
  "Hot Sauce",
  "Soy Sauce",
  "Teriyaki Sauce",
  "Chili Sauce",
  "Garlic Sauce",
  "Tahini",
  "Hummus",
  "Pesto",

  // 🧂 Spices & Seasonings
  "Salt",
  "Black Pepper",
  "White Pepper",
  "Paprika",
  "Chili Powder",
  "Cumin",
  "Coriander Powder",
  "Turmeric",
  "Oregano",
  "Basil",
  "Thyme",
  "Rosemary",
  "Cinnamon",
  "Nutmeg",
  "Garlic Powder",
  "Onion Powder",
  "Italian Seasoning",

  // 🍓 Fruits
  "Apple",
  "Banana",
  "Orange",
  "Lemon",
  "Lime",
  "Strawberry",
  "Blueberry",
  "Mango",
  "Pineapple",
  "Grapes",
  "Pomegranate",

  // 🍰 Desserts & Sweet Items
  "Sugar",
  "Brown Sugar",
  "Honey",
  "Maple Syrup",
  "Chocolate Chips",
  "Cocoa Powder",
  "Vanilla Extract",
  "Flour",
  "Baking Powder",
  "Baking Soda",

  // 🥤 Drinks & Extras
  "Ice",
  "Sparkling Water",
  "Mineral Water",
  "Tea Leaves",
  "Coffee Beans",
];

export const services = [
  {
    icon: "ri-truck-line",
    title: "Fast Delivery",
    description:
      "Get your food delivered to your doorstep within 30 minutes. We ensure hot and fresh delivery every time.",
    color: "from-orange-400 to-orange-500",
  },
  {
    icon: "ri-restaurant-line",
    title: "Quality Food",
    description:
      "We use only the freshest ingredients and maintain the highest quality standards in food preparation.",
    color: "from-green-400 to-green-500",
  },
  {
    icon: "ri-customer-service-2-line",
    title: "24/7 Support",
    description:
      "Our customer support team is available round the clock to assist you with any queries or concerns.",
    color: "from-pink-400 to-pink-500",
  },
  {
    icon: "ri-shield-check-line",
    title: "Safe & Hygienic",
    description:
      "We follow strict hygiene protocols and safety measures to ensure your food is prepared in a clean environment.",
    color: "from-indigo-400 to-indigo-500",
  },
  {
    icon: "ri-price-tag-3-line",
    title: "Best Prices",
    description:
      "Enjoy delicious food at competitive prices with regular discounts and special offers for our customers.",
    color: "from-yellow-400 to-yellow-500",
  },
  {
    icon: "ri-star-smile-line",
    title: "Easy Ordering",
    description:
      "Simple and intuitive ordering process. Order your favorite food in just a few clicks from anywhere.",
    color: "from-teal-400 to-teal-500",
  },
];

export const restaurantStats = [
  { icon: "ri-user-smile-line", value: "10K+", label: "Happy Customers" },
  { icon: "ri-restaurant-line", value: "500+", label: "Dishes Available" },
  { icon: "ri-star-smile-line", value: "4.9", label: "Average Rating" },
  { icon: "ri-truck-line", value: "50K+", label: "Orders Delivered" },
];

export const publicPages = [
  {
    id: 1,
    title: "About Us",
    slug: "about",
    content:
      "We are passionate about delivering delicious, healthy food right to your doorstep...",
    status: "published",
    lastModified: "2025-01-15",
  },
  {
    id: 2,
    title: "Privacy Policy",
    slug: "privacy-policy",
    content: "Your privacy is important to us...",
    status: "published",
    lastModified: "2025-01-10",
  },
  {
    id: 3,
    title: "Terms & Conditions",
    slug: "terms",
    content: "By using our service, you agree to these terms...",
    status: "published",
    lastModified: "2025-01-10",
  },
  {
    id: 4,
    title: "FAQ",
    slug: "faq",
    content: "Frequently Asked Questions...",
    status: "published",
    lastModified: "2025-01-12",
  },
];

export const adminOrders = [
  {
    id: "#ORD-001",
    customer: "John Doe",
    customerEmail: "john@example.com",
    customerPhone: "+2 234 567 8900",
    deliveryAddress: "123 Main Street, New York, NY 10001",
    items: 3,
    total: 45.97,
    status: "preparing",
    time: "5 min ago",
    date: "Jan 15, 2025",
    dishes: [
      { name: "Healthy Salad Bowl", quantity: 2, price: 12.99 },
      { name: "Fresh Orange Juice", quantity: 1, price: 5.99 },
    ],
    paymentMethod: "Credit Card",
    subtotal: 41.97,
    tax: 2.0,
    deliveryFee: 2.0,
  },
  {
    id: "#ORD-002",
    customer: "Jane Smith",
    customerEmail: "jane@example.com",
    customerPhone: "+2 234 567 8901",
    deliveryAddress: "456 Oak Avenue, Los Angeles, CA 90001",
    items: 2,
    total: 28.98,
    status: "delivered",
    time: "15 min ago",
    date: "Jan 15, 2025",
    dishes: [{ name: "Caesar Salad", quantity: 2, price: 10.99 }],
    paymentMethod: "PayPal",
    subtotal: 21.98,
    tax: 5.0,
    deliveryFee: 2.0,
  },
  {
    id: "#ORD-003",
    customer: "Mike Johnson",
    customerEmail: "mike@example.com",
    customerPhone: "+2 234 567 8902",
    deliveryAddress: "789 Pine Road, Chicago, IL 60601",
    items: 4,
    total: 52.96,
    status: "on-the-way",
    time: "20 min ago",
    date: "Jan 15, 2025",
    dishes: [
      { name: "Protein Bowl", quantity: 2, price: 13.99 },
      { name: "Caesar Salad", quantity: 2, price: 10.99 },
    ],
    paymentMethod: "Cash on Delivery",
    subtotal: 49.96,
    tax: 1.0,
    deliveryFee: 2.0,
  },
];
export const customers = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "+1 234 567 8900",
    address: "123 Main Street",
    city: "New York",
    zipCode: "10001",
    avatar:
      "https://readdy.ai/api/search-image?query=professional%20friendly%20male%20person%20smiling%20portrait%20clean%20white%20background%20professional%20photography&width=200&height=200&seq=user1&orientation=squarish",
    status: "active",
    joinDate: "2024-01-15",
    totalOrders: 24,
    totalSpent: 456.8,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "+1 234 567 8901",
    address: "456 Oak Avenue",
    city: "Los Angeles",
    zipCode: "90001",
    avatar:
      "https://readdy.ai/api/search-image?query=professional%20friendly%20female%20person%20smiling%20portrait%20clean%20white%20background%20professional%20photography&width=200&height=200&seq=user2&orientation=squarish",
    status: "active",
    joinDate: "2024-02-20",
    totalOrders: 18,
    totalSpent: 342.5,
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike@example.com",
    phone: "+1 234 567 8902",
    address: "789 Pine Road",
    city: "Chicago",
    zipCode: "60601",
    avatar:
      "https://readdy.ai/api/search-image?query=professional%20friendly%20male%20person%20smiling%20portrait%20clean%20white%20background%20professional%20photography&width=200&height=200&seq=user3&orientation=squarish",
    status: "inactive",
    joinDate: "2024-03-10",
    totalOrders: 5,
    totalSpent: 89.99,
  },
];
